function [g_x_phi] = g_x_phi_fun(x,phi,lambda_AP,lambda_b,E_L,L_min,L_max)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
[M, N] = size(phi);

for m = 1:M
    for n = 1:N
%         a = @(omega,t) t.*abs(sin(phi(m,n)-omega))./sin(phi(m,n));
%         
%         g_x_phi(m,n) = exp(-lambda_AP*(...
%                        2*integral2(@(omega,t)...
%                        t.*exp(-lambda_b*t.^2.*abs(sin(phi(m,n)-omega)).*sin(omega)/(2*sin(phi(m,n)))).*((0 <= a(omega,t)) & (a(omega,t) < L_min))...
%                        +t.*exp(-lambda_b/(L_max-L_min)*((a(omega,t).^2-L_min^2)/2.*t.*sin(omega)-(a(omega,t).^3-L_min^3)/6*sin(phi(m,n)).*sin(omega)./abs(sin(phi(m,n)-omega))+(L_max-a(omega,t)).*t.^2.*abs(sin(phi(m,n)-omega)).*sin(omega)/(2*sin(phi(m,n))))).*((L_min <= a(omega,t)) & (a(omega,t) < L_max))...
%                        +t.*exp(-lambda_b*(E_L*t.*sin(omega)-1/(L_max-L_min)*(L_max^3-L_min^3)/6*sin(phi(m,n)).*sin(omega)./abs(sin(phi(m,n)-omega)))).*(L_max <= a(omega,t))...
%                        , 0, pi/2, 0, x(m,n), 'RelTol', 1e-1, 'AbsTol', 1e-1)...
%                        +2*integral2(@(omega,t) t.*exp(-lambda_b*E_L*t.*sin(omega)), 0, pi/2, 0, x(m,n), 'RelTol', 1e-1, 'AbsTol', 1e-1)))...
%                        .*x(m,n).*exp(-lambda_b*E_L*x(m,n).*sin(phi(m,n)));
        g_x_phi(m,n) = exp(-lambda_AP*(...
                       2*integral2(@(omega,t) P_LOS_fun(t, omega, phi(m,n), lambda_b,E_L,L_min,L_max), 0, pi/2, 0, x(m,n), 'RelTol', 1e-1, 'AbsTol', 1e-1)...
                       +2*integral2(@(omega,t) t.*exp(-lambda_b*E_L*t.*sin(omega)), 0, pi/2, 0, x(m,n), 'RelTol', 1e-1, 'AbsTol', 1e-1)))...
                       *x(m,n)*exp(-lambda_b*E_L*x(m,n).*sin(phi(m,n)));
    end
end
end